version: 2

jobs:
  build:
    docker:
      - image: "rikorose/gcc-cmake:gcc-7"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Build
          command: 'make'
            - store_artifacts:
                path: /bin/final_build

workflows:
    version: 2
    main:
        jobs:
            - build_and_save
